sudo: required

language: cpp

env:
  global:
    - CATKIN_WS=~/catkin_ws
    - CATKIN_WS_SRC=${CATKIN_WS}/src

matrix:
  include:
    - name: "Xenial Kinetic"
      dist: xenial
      env: CI_ROS_DISTRO=kinetic
    - name: "Bionic Melodic"
      dist: bionic
      env: CI_ROS_DISTRO=melodic

before_install:
  - sudo apt install -qq -y gnupg
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu ${TRAVIS_DIST} main" > /etc/apt/sources.list.d/ros-latest.list'
  - sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-rosdep python-catkin-tools
  - sudo rosdep init
  - rosdep update

before_script:
  - rosdep install --from-paths ${TRAVIS_BUILD_DIR} -i -r -y --rosdistro ${CI_ROS_DISTRO}
  - source /opt/ros/${CI_ROS_DISTRO}/setup.bash
  - mkdir -p ${CATKIN_WS_SRC}
  - ln -s ${TRAVIS_BUILD_DIR} ${CATKIN_WS_SRC}

script:
  - cd ${CATKIN_WS}
  - catkin init
  - catkin config --install
    # Build [and Install] packages
  - catkin build --limit-status-rate 0.1 --no-notify -DCMAKE_BUILD_TYPE=Release
    # Run tests
  - catkin run_tests
  - catkin_test_results build
    # Lint package files
  - sudo apt-get install -qq -y python-catkin-lint
  - catkin lint -W2 --strict --explain src
