# http://wiki.ros.org/base_local_planner
TrajectoryPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.2
  min_vel_x: 0.05

  max_vel_theta:  1.5
  min_vel_theta: -1.5
  min_in_place_vel_theta: 0.5

  acc_lim_x: 0.75
  acc_lim_theta: 1.0

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.3 # about 17 degrees
  xy_goal_tolerance: 0.1 # 10 cm

# Forward Simulation Parameters
  sim_time: 1.7
  vx_samples: 8
  vtheta_samples: 20

# Trajectory Scoring Parameters
  meter_scoring: true
  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.05
  heading_lookahead: 0.3
  dwa: true

# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05

# Differential-drive robot configuration
  holonomic_robot: false
  max_vel_y: 0.0
  min_vel_y: 0.0
  acc_lim_y: 0.0
  vy_samples: 1
  