max_obstacle_height: 0.60
obstacle_range: 2.5 #1.0
raytrace_range: 3.0
# Obstacle Cost Shaping (http://wiki.ros.org/costmap_2d/hydro/inflation)
# distance a circular robot should be clear of the obstacle
robot_radius: 0.1675
# if the robot is not circular
# footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
# max. distance from an obstacle at which costs are incurred for
# planning paths.
inflation_radius: 0.5
# exponential rate at which the obstacle cost drops off (default: 10)
# cost_scaling_factor: 5  

# voxel map configuration; z-voxels 0 are filled by bumpers and 1 by
# laser scan (kinect)
map_type: voxel
origin_z: 0.0
z_resolution: 0.1
z_voxels: 1
publish_voxel_map: false

observation_sources: bump
# http://wiki.ros.org/navigation/Troubleshooting#Missing_Obstacles_in_Costmap2D
# Note that the max_obstacle_height is very important too!
bump: {
  data_type: PointCloud2, 
  topic: /mobile_base/sensors/bumper_pointcloud, 
  marking: true, 
  clearing: false,
  min_obstacle_height: 0.0,
  max_obstacle_height: 0.1
}
# scan: {
#         data_type: LaserScan,
#         topic: mobile_base/laser/scan,
#         marking: true,
#         clearing: true,
#         min_obstacle_height: 0.0,
#         max_obstacle_height: 3
#       }