obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.16, -0.16], [-0.16, 0.16], [0.19, 0.16], [0.24, 0.0], [0.19, -0.16]]
footprint_padding: 0.01
inflation_radius: 0.5
max_obstacle_height: 1.0
min_obstacle_height: 0.0
observation_sources: bump
bump: {data_type: PointCloud2, topic: /mobile_base/sensors/bumper_pointcloud , marking: true, clearing: false}