local_costmap:
   global_frame: /odom
   robot_base_frame: /base_footprint
   update_frequency: 5.0
   publish_frequency: 5.0
   static_map: false
   rolling_window: true
   width: 2.5
   height: 2.5
   resolution: 0.01
   transform_tolerance: 0.5
