# XBox 360 wired controller
joy_teleop:
  ros__parameters:
    piloting:
      type: topic
      interface_type: "geometry_msgs/msg/Twist"
      topic_name: cmd_vel
      deadman_buttons: []  # No deadman buttons
      axis_mappings:
        linear-x:
          axis: 4  # Right thumb (up/down)
          scale: 0.4
          offset: 0.0
        angular-z:
          axis: 3  # Right thumb stick (left/right)
          scale: 2.5
          offset: 0.0
