<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="create_base" params="diffdrive_update_rate:=40 wheel_separation wheel_radius:=0.036 wheel_width:=0.024 wheel_torque:=0.5 wheel_accel:=0.5 mass_kg:=3.5 base_diameter *mesh visualize:=false">

    <xacro:include filename="$(find ca_description)/urdf/create_base_gazebo.urdf.xacro"/>
    <xacro:include filename="$(find ca_description)/urdf/create_caster_wheel.xacro"/>
    <xacro:include filename="$(find ca_description)/urdf/create_wheel.xacro"/>
    <xacro:include filename="$(find ca_description)/urdf/sensors/imu_sensor.xacro"/>
    <xacro:include filename="$(find ca_description)/urdf/sensors/wall_sensor.xacro"/>
    <xacro:include filename="$(find ca_description)/urdf/sensors/cliff_sensors.xacro"/>

    <link name="base_footprint">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
      <material name="Green" />
    </visual>

    <collision>
      <origin xyz="0 0 0.017" rpy="0 0 0" />
      <geometry>
        <box size="0.001 0.001 0.001" />
      </geometry>
    </collision>
    </link>

    <link name="base_link">
      <inertial>
        <mass value="2" />
        <origin xyz="0 0 0.0" />
        <inertia ixx="0.01" ixy="0.0" ixz="0.0" iyy="0.01" iyz="0.0" izz="0.5" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0.0308" rpy="0 0 0" />
        <geometry>
          <xacro:insert_block name="mesh" />
        </geometry>
      </visual>

      <collision>
        <origin xyz="0.0 0.0 0.0308" rpy="0 0 0" />
        <geometry>
          <cylinder length="0.0611632" radius="0.16495" />
        </geometry>
      </collision>
    </link>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 0.017" rpy="0 0 0" />
      <parent link="base_footprint" />
      <child link="base_link" />
    </joint>

    <xacro:wall_sensor visualize="${visualize}"/>
    <xacro:cliff_sensors visualize="${visualize}"/>
    <xacro:imu_sensor/>

    <xacro:create_wheel prefix="left" y_offset="${wheel_separation / 2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>
    <xacro:create_wheel prefix="right" y_offset="${wheel_separation / -2}" wheel_radius="${wheel_radius}" wheel_width="${wheel_width}"/>
    <xacro:caster_wheel/>

    <!-- Simulation sensors -->
    <xacro:sim_create_base/>
  </xacro:macro>
</robot>
